services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    volumes:
      - /home/cloud/docker/minecraft/data:/data
    stdin_open: true
    tty: true    
    restart: always
    user: "${UID}:${GID}"
